# Generated by Django 5.0.3 on 2024-03-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descriptions',
            new_name='description',
        ),
    ]
