# Generated by Django 5.0.3 on 2024-03-16 13:19

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='expeditions.comment', verbose_name='Комментарии'),
        ),
    ]
