# Generated by Django 5.0.3 on 2024-03-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_descriptions_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Место отдыха', 'verbose_name_plural': 'Места отдыха'},
        ),
    ]
