# Generated by Django 5.0.3 on 2024-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditions',
            options={'verbose_name': 'Экспедиция', 'verbose_name_plural': 'Экспедиции'},
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='rating',
            field=models.FloatField(verbose_name='Средний рейтинг'),
        ),
    ]
