# Generated by Django 5.0.3 on 2024-03-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_alter_expeditions_options_alter_touroperator_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_the_newsletter',
            field=models.BooleanField(default=False, verbose_name='Подписка на рассылку'),
        ),
    ]
